[UniversalParameters]
stepsize = 1.0
maxChrom = 5.0
deathRate = 0.1
misRate = 0.01
finalDay = 300
startPop = 1
starting_copy_number = [2,2,2,2,2]
max_cell_cycle_duration = 100

[SpatialParameters]
"Γ" = 500
"Γₑ" = 100000
"ϕ" = 0.5
"Ξ" = 0.02
"χ" = 0.0
"δ" = 0.01
Lp = [650.0,650.0]
Np = [21,21]
k = 0.0001
E_vessel = 1.0
stochasticThreshold=1000

[Options]
debugging = 3
compartmentMinimum = false
replating = false
maxPop = 1e5
progress_check = true
saveat = 0.1
interpolation_order = 2

[Files]

blood_vessel_file = "6069_vessels.txt"
copy_number_file = "birthLandscapeBrainCancer.txt"
birth_rate_file = "GrowthRate_brain_cancer_CLs.txt"