debugging = 3
stepsize = 1.0
minChrom = 1.0
maxChrom = 2.0
deathRate = 0.01
misRate = 0.15
finalDay = 2.0
replating = true
maxPop = 1e6
startPop = 1e3
compartmentMinimum = false
"Γ" = 0.1
"Γₑ" = 0.5
"ϕ" = 0.05
"Ξ" = 0.02
"χ" = 1.0
"δ" = 0.05
Np = [21,21]