debugging = 3
stepsize = 1.0
maxChrom = 2.0
deathRate = 0.0
misRate = 0.01
finalDay = 1.0
replating = true
maxPop = 1e6
startPop = 1e3
compartmentMinimum = false
"Γ" = 0.05
"Γₑ" = 0.5
"ϕ" = 0.02
"Ξ" = 0.02
"χ" = 0.01
"δ" = 0.05
Np = [21,21]
progress_check = true
interpolation_order = 2