debugging = 3
stepsize = 1.0
maxChrom = 2.0
deathRate = 0.0
misRate = 0.1
finalDay = 5.0
replating = true
maxPop = 1e6
startPop = 1e3
compartmentMinimum = false
"Γ" = 0.01
"Γₑ" = 5.0
"ϕ" = 0.02
"Ξ" = 0.02
"χ" = 0.1
"δ" = 0.0005
Np = [21,21]
progress_check = true
max_cell_cycle_duration = 100
interpolation_order = 2